### PR TITLE
feat : three APIs(Categories/attraction)

### PR DESCRIPTION
**Pull request by yujen77300**
老師您好 
我是黃育仁 ，提供測試網址如下
1. http://54.150.244.240:3000/api/categories
2. http://54.150.244.240:3000/api/attraction/10
3. http://54.150.244.240:3000/api/attractions?page=4
4. http://54.150.244.240:3000/api/attractions?page=0&keyword=藝文館所
再麻煩您檢查
謝謝

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Some issues below:

1. Response format of attraction data is incorrect.
2. Use `LIMIT` to do range selection, not do it in your own code.

Solve them and re-request review.

**Comment by yujen77300** [comment]
老師 您好 剛剛已經更改完attraction回應的格式，並透過sql的limit來限制筆數
謝謝

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by yujen77300** [comment]
了解，已重新增加reviewer，再麻煩老師確認了

**Review by cwpeng — APPROVED** [review]
OK. Done.

Suggest using `GROUP_CONCAT` and `JOIN` to get attractio data and images all at once, much better than get attraction images one by one.

**Pull request merged**
